# Generated by Django 5.0.2 on 2024-11-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_care_instructions_product_key_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='care_instructions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='key_features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='other_information',
        ),
        migrations.RemoveField(
            model_name='product',
            name='technical_details',
        ),
    ]
